export const languageList = [
    { name: 'polski', code: 'pol' },
    { name: 'angielski', code: 'eng' },
    { name: 'arabski', code: 'ara' },
    { name: 'bułgarski', code: 'bul' },
    { name: 'chiński upr', code: 'chs' },
    { name: 'chiński trad', code: 'cht' },
    { name: 'chorwacki', code: 'hrv' },
    { name: 'czeski', code: 'cze' },
    { name: 'duński', code: 'dan' },
    { name: 'fiński', code: 'fin' },
    { name: 'francuski', code: 'fre' },
    { name: 'grecki', code: 'gre' },
    { name: 'hiszpański', code: 'spa' },
    { name: 'holenderski', code: 'dut' },
    { name: 'japoński', code: 'jpn' },
    { name: 'koreański', code: 'kor' },
    { name: 'niemiecki', code: 'ger' },
    { name: 'portugalski', code: 'por' },
    { name: 'rosyjski', code: 'rus' },
    { name: 'słoweński', code: 'slv' },
    { name: 'szwedzki', code: 'swe' },
    { name: 'turecki', code: 'tur' },
    { name: 'węgierski', code: 'hun' },
    { name: 'włoski', code: 'ita' },
]